- app/Livewire/Admin/Roles/RoleDelete.php
- app/Livewire/Admin/Roles/RoleForm.php
- app/Livewire/Admin/Roles/RolesTable.php
- app/Livewire/Forms/Admin/Roles/Frm.php
- app/Livewire/Utilities/DataPaginator.php
- app/Models/Role.php
- app/Utils/Threads/DeleteThread.php
- app/Utils/Threads/FormThread.php
- app/Utils/Threads/TableThread.php
- lang/en/messages.php
- lang/es/messages.php
- resources/js/bootstrap.js
- resources/views/components/admin/roles/data-card.blade.php
- resources/views/components/admin/roles/form-card.blade.php
- resources/views/components/forms/error.blade.php
- resources/views/components/forms/label.blade.php
- resources/views/components/forms/text-area.blade.php
- resources/views/components/modals/modal.blade.php
- resources/views/components/utils/info-message.blade.php
- resources/views/livewire/admin/roles/role-delete.blade.php
- resources/views/livewire/admin/roles/role-form.blade.php
- resources/views/livewire/admin/roles/roles-table.blade.php
Add the Roles module with create, update and delete action (validation to delete default or main roles of app not added yet), also update some blade anonymous components for enable dark mode, also create the table, form and delete threads to re-use in livewire components.
> Add Roles module (v0.4.0)

- app/Livewire/Admin/Roles/ManageRolePermissions.php
- app/Livewire/Admin/Roles/RolesTable.php
- app/Models/Permission.php
- app/Models/Role.php
- app/Models/User.php
- lang/en/messages.php
- lang/es/messages.php
- resources/views/components/buttons/circle-icon-button.blade.php
- resources/views/components/tables/dates-columns.blade.php
- resources/views/livewire/admin/roles/manage-role-permissions.blade.php
- resources/views/livewire/admin/roles/roles-table.blade.php
Update RolesTable.php wire component, Role, User and Permission models to include new functions, also update messages.php language files of en and es paths to add 'permission' key in 'models' and set others in menu, also update cicle-icon-button.blade.php to enable dark gradient level as prop, also update dates-columns to enable for dark mode, finaly create the ManageRolePermissions wire component to enable manage of permisssions of a one role - 14-11-2023
> v0.5.0 - Update Roles module

- app/Http/Controllers/admin/UserController.php
- app/Livewire/Admin/Users/UserDelete.php
- app/Livewire/Admin/Users/UserForm.php
- app/Livewire/Admin/Users/UsersTable.php
- app/Livewire/Forms/Admin/Users/Frm.php
- app/Utils/Threads/FormThread.php
- app/Utils/Threads/TableThread.php
- lang/en/messages.php
- lang/es/messages.php
- resources/views/components/admin/users/data-card.blade.php
- resources/views/components/admin/users/form-card.blade.php
- resources/views/components/layouts/navbars/admin-navbar.blade.php
- resources/views/components/tables/dates-columns.blade.php
- resources/views/livewire/admin/roles/roles-table.blade.php
- resources/views/livewire/admin/users/user-delete.blade.php
- resources/views/livewire/admin/users/user-form.blade.php
- resources/views/livewire/admin/users/users-table.blade.php
- resources/views/pages/admin/users/index.blade.php
- routes/web.php
Create users modules with your files, then create UsersTable, UserForm, UserDelete, Frm of users, data-card.blade.php and form-card.blade of users, also update messages.php language files, also update web.php and admin-navbar.blade.php files to enable 'users' route, in table component the displaying and searching of data is working (CRUD NOT AVAILABLE FOR NOW) - 14-11-2023
> v0.6.0 - Create Users module

- README.md
- app/Http/Controllers/admin/UserController.php
- app/Livewire/Admin/Users/ManageUserPermissions.php
- app/Livewire/Admin/Users/UserForm.php
- app/Livewire/Admin/Users/UsersTable.php
- app/Livewire/Forms/Admin/Users/Frm.php
- app/Models/User.php
- lang/en/messages.php
- lang/es/messages.php
- resources/css/app.css
- resources/views/components/admin/users/form-card.blade.php
- resources/views/components/forms/select.blade.php
- resources/views/components/layouts/navbars/admin-navbar.blade.php
- resources/views/livewire/admin/users/manage-user-permissions.blade.php
- resources/views/livewire/admin/users/user-delete.blade.php
- resources/views/livewire/admin/users/users-table.blade.php
Update all user modules files to enable CRUD, then adition, updating, deletion and manage of users permission, new keys added into messages.php language files, add required style in app.css, update User model to make wireable and create ManageUserPermissions wire component, also include into UserTable.php wire component - 15-11-2023
> v0.7.0 - Update Users module

- app/Http/Controllers/admin/PermissionController.php
- app/Livewire/Admin/Permissions/PermissionDelete.php
- app/Livewire/Admin/Permissions/PermissionForm.php
- app/Livewire/Admin/Permissions/PermissionsTable.php
- app/Livewire/Forms/Admin/Permissions/Frm.php
- app/Models/Permission.php
- resources/views/components/admin/permissions/data-card.blade.php
- resources/views/components/admin/permissions/form-card.blade.php
- resources/views/components/layouts/navbars/admin-navbar.blade.php
- resources/views/livewire/admin/permissions/permission-delete.blade.php
- resources/views/livewire/admin/permissions/permission-form.blade.php
- resources/views/livewire/admin/permissions/permissions-table.blade.php
- resources/views/pages/admin/permissions/index.blade.php
- routes/web.php
Create Permission module with all files to enable CRUD - 15-11-2023
> Add Permissions Module

- app/Http/Controllers/PersonController.php
- app/Http/Controllers/admin/UserController.php
- app/Livewire/Forms/Sys/People/Frm.php
- app/Livewire/Sys/People/PeopleTable.php
- app/Livewire/Sys/People/PersonDelete.php
- app/Livewire/Sys/People/PersonForm.php
- app/Models/Sys/Person.php
- config/admin/permissions.php
- database/migrations/2023_11_15_211127_create_people_table.php
- lang/en/messages.php
- lang/es/messages.php
- resources/views/components/layouts/navbars/sys-navbar.blade.php
- resources/views/components/sys/people/data-card.blade.php
- resources/views/components/sys/people/form-card.blade.php
- resources/views/livewire/sys/people/people-table.blade.php
- resources/views/livewire/sys/people/person-delete.blade.php
- resources/views/livewire/sys/people/person-form.blade.php
- resources/views/pages/sys/people/index.blade.php
- routes/web.php
Create people module with table, form and delete components, create Person controller but not use, also create index view of people module but not use it, update web.php routes to add '/people' route with full page component of this module, also create Frm form to save data of this module, enable People module to display, create, edit and delete data, also enable manage of user permission from people module, as well update UserController to make static functions to store and update a user resource (pending call this from User module), update permissions.php config file to add permission of people module, also update messages.php to add and set some keys, finaly update sys-navbar.blade.php to enable People access button - 18-11-2023
> v0.9.0 - Create People module

- app/Livewire/Forms/Admin/Users/Frm.php
- app/Livewire/Forms/Sys/Events/Frm.php
- app/Livewire/Sys/Events/EventDelete.php
- app/Livewire/Sys/Events/EventForm.php
- app/Livewire/Sys/Events/EventsTable.php
- app/Models/Permission.php
- app/Models/Sys/Event.php
- app/Utils/Threads/FormThread.php
- config/admin/permissions.php
- database/migrations/2023_11_18_222758_create_events_table.php
- lang/en/messages.php
- lang/es/messages.php
- resources/views/components/layouts/navbars/sys-navbar.blade.php
- resources/views/components/sys/events/data-card.blade.php
- resources/views/components/sys/events/form-card.blade.php
- resources/views/livewire/admin/permissions/permissions-table.blade.php
- resources/views/livewire/sys/events/event-delete.blade.php
- resources/views/livewire/sys/events/event-form.blade.php
- resources/views/livewire/sys/events/events-table.blade.php
- resources/views/pages/admin/permissions/index.blade.php
- routes/web.php
Create events module with table, form and delete components, update web.php routes to add '/events' route with full page component of this module, also create Frm form to save data of this module, enable Events module to display, create, edit and delete data, finaly update permissions.php config file to add permission of events module, also update messages.php to add and set some keys, finaly update sys-navbar.blade.php to enable Event access button - 19-11-2023
> v0.10.0 - Create Events module

- app/Livewire/Forms/Sys/Events/Attendances/Frm.php
- app/Livewire/Sys/Events/Attendances/AttendanceDelete.php
- app/Livewire/Sys/Events/Attendances/AttendanceForm.php
- app/Livewire/Sys/Events/Attendances/AttendancesTable.php
- app/Models/Permission.php
- app/Models/Sys/EventAttendance.php
- config/admin/permissions.php
- database/migrations/2023_11_19_144922_create_event_attendances_table.php
- lang/en/messages.php
- lang/es/messages.php
- resources/views/components/sys/events/attendances/data-card.blade.php
- resources/views/components/sys/events/attendances/form-card.blade.php
- resources/views/livewire/sys/events/attendances/attendance-delete.blade.php
- resources/views/livewire/sys/events/attendances/attendance-form.blade.php
- resources/views/livewire/sys/events/attendances/attendances-table.blade.php
- routes/web.php
Create event attendances module with table, form and delete components, update web.php routes to add '/events/attendances' route with full page component of this module, also create Frm form to save data of this module, enable Event Attendances module to display, create, edit and delete data, also update permissions.php config file to add permission of this new module, also update messages.php to add and set some keys, finaly update EventsTable component for enable access to attendances of a one event - 19-11-2023
> v0.11.1 - Create Event Attendances module

- app/Livewire/Forms/Sys/Activities/Frm.php
- app/Livewire/Sys/Activities/ActivitiesTable.php
- app/Livewire/Sys/Activities/ActivityDelete.php
- app/Livewire/Sys/Activities/ActivityForm.php
- app/Models/Permission.php
- app/Models/Sys/Activity.php
- config/admin/permissions.php
- database/migrations/2023_11_19_213538_create_activities_table.php
- lang/en/messages.php
- lang/es/messages.php
- resources/views/components/layouts/navbars/sys-navbar.blade.php
- resources/views/components/sys/activities/data-card.blade.php
- resources/views/components/sys/activities/form-card.blade.php
- resources/views/livewire/sys/activities/activities-table.blade.php
- resources/views/livewire/sys/activities/activity-delete.blade.php
- resources/views/livewire/sys/activities/activity-form.blade.php
- routes/web.php
Create activities module with table, form and delete components, update web.php routes to add '/activities' route with full page component of this module, also create Frm form to save data of this module, enable this module to display, create, edit and delete data, also update permissions.php config file to add permission of this new module, also update messages.php to add and set some keys, finaly update sys-navbar.blade.php for enable access to activities module - 20-11-2023
> v0.12.0 - Create Activities module

- app/Livewire/Forms/Sys/Activities/Frm.php
- app/Livewire/Forms/Sys/People/Frm.php
- app/Livewire/Portal/Activities.php
- app/Livewire/Portal/Dashboard.php
- app/Livewire/Portal/Home.php
- app/Models/Sys/Activity.php
- app/Models/Sys/Event.php
- app/Models/Sys/Person.php
- database/migrations/2023_11_15_211127_create_people_table.php
- database/migrations/2023_11_19_213538_create_activities_table.php
- lang/en/messages.php
- lang/es/messages.php
- resources/js/bootstrap.js
- resources/js/sweet/Sweet.js
- resources/views/components/layouts/pages/base-layout.blade.php
- resources/views/components/sys/activities/data-card.blade.php
- resources/views/components/sys/activities/form-card.blade.php
- resources/views/components/sys/people/form-card.blade.php
- resources/views/livewire/portal/activities.blade.php
- resources/views/livewire/portal/dashboard.blade.php
- resources/views/livewire/portal/home.blade.php
- resources/views/livewire/sys/activities/activities-table.blade.php
- resources/views/pages/portal/index.blade.php
- routes/web.php
Create portal module with home, dashboard and activities components, create these files to enable register of attendance for one activity by one person, also update Activity model and migration to add new attributes and functions, also update Event model to add new functions and update Person migration to remove not null restriction in 'sex' column, also update messages.php language files to add new keys, also update Sweet.js to enable displaying of alerts, finaly update web.php routes to add '/portal/home', '/portal/event/activities' routes - 22-11-2023
> v0.14.0 - Create portal module

- .env.example
- app/Livewire/Sys/Activities/RegisterAttendance.php
- app/Models/Sys/EventAttendance.php
- app/Models/Sys/Person.php
- database/seeders/ActivitySeeder.php
- resources/views/components/layouts/footers/portal-footer.blade.php
- resources/views/components/sys/activities/info-card.blade.php
- resources/views/livewire/portal/virtual-card.blade.php
- resources/views/livewire/sys/activities/activities-table.blade.php
- resources/views/livewire/sys/activities/register-attendance.blade.php
update RegisterAttendance component to include set of payment status in this component, also include info of event attendance for selected person, also add buttons to remove selected person, set as paid in the footer bottom actions of modal, also update fix writing of institutions in EventAttendance model, also update Person model to generate bar code with black lines and set height of this, then update VirtualCard component ui to generate bar code with white background and black lines, finally fix grammar in footer and lock access to register attendance button from activities table when activity is closed, also include more info in info-card.blade.php of activity - 28-11-2023
> v1.0 - Version 1

- app/Livewire/Sys/Activities/RegisterAttendance.php
update this component to disabled autoload of data for dev testing - 28-11-2023
> v1.1.0 - Update RegisterAttendance component

- app/Livewire/Admin/Permissions/PermissionsTable.php
- app/Livewire/Admin/Roles/RolesTable.php
- app/Livewire/Admin/Users/UsersTable.php
- routes/web.php
Replace routes of users, permissions and roles by full page components - 28-11-2023
> v1.1.3 - Update web.php routes file

- app/Livewire/Forms/Sys/Activities/Attendances/Frm.php
- app/Models/Sys/ActivityAttendance.php
- resources/views/livewire/portal/activities.blade.php
Update activity attendances module to fix isssue when user try update attendance, then update ActivityAttendance model to add function to determinate if the attendance can be updated, finaly improve UI of activities to display no slots info and show full date in each activity - 30-11-2023
> v1.1.4 - Update Activity Attendances module

- app/Livewire/Forms/Sys/Events/Attendances/Frm.php
- app/Livewire/Forms/Sys/Events/Frm.php
- app/Livewire/Portal/Dashboard.php
- app/Livewire/Sys/Events/Attendances/AttendancesTable.php
- app/Livewire/Sys/Events/CertificateSetupForm.php
- app/Livewire/Sys/Events/EventDelete.php
- app/Livewire/Sys/Events/EventsTable.php
- app/Models/Sys/Event.php
- app/Models/Sys/EventAttendance.php
- app/Models/Sys/Person.php
- app/Utils/CommonUtils.php
- composer.json
- composer.lock
- config/admin/permissions.php
- database/migrations/2023_12_10_195049_add_columns_to_events_table.php
- database/migrations/2023_12_12_172754_add_column_approve_certificate_manually_to_event_attendances_table.php
- lang/en/messages.php
- lang/es/messages.php
- resources/views/components/sys/events/attendances/form-card.blade.php
- resources/views/components/sys/events/form-card.blade.php
- resources/views/livewire/portal/dashboard.blade.php
- resources/views/livewire/sys/activities/register-attendance.blade.php
- resources/views/livewire/sys/events/attendances/attendances-table.blade.php
- resources/views/livewire/sys/events/certificate-setup-form.blade.php
- resources/views/livewire/sys/events/event-form.blade.php
- resources/views/livewire/sys/events/events-table.blade.php
- resources/views/pages/portal/certificates/certificate-pdf.blade.php
more info in commits of version 1.2.0, 1.3.0 and 1.4.0
> V1.4.0 Enable certificate process

- app/Livewire/Portal/Dashboard.php
- config/app.php
- resources/views/pages/portal/certificates/certificate-pdf.blade.php
Update the certificate-pdf.blade template to fix issue when 'dates_range' haven't data or is not present in the template, also update app.php config file to add provider and aliases of PDF, finally update the Dashboard component to replace generation of PDF with 'dompdf.wrapper' instance - 18-12-2023
> v1.4.1 - Update the Certificate module

- .gitignore
- app/Livewire/Forms/Sys/Events/Frm.php
- app/Livewire/Portal/Dashboard.php
- app/Livewire/Portal/Home.php
- app/Livewire/Portal/Register.php
- app/Livewire/Portal/RegisterEventAttendance.php
- app/Livewire/Portal/VirtualCard.php
- app/Livewire/Sys/Events/EventsTable.php
- app/Livewire/Sys/Events/VirtualCardSetupForm.php
- app/Models/Sys/Event.php
- app/Models/Sys/EventAttendance.php
- config/admin/permissions.php
- database/migrations/2024_01_04_224253_add_column_virtual_card_setup_to_events_table.php
- lang/en/messages.php
- lang/es/messages.php
- resources/views/components/layouts/footers/portal-footer.blade.php
- resources/views/components/portal/events/attendances/register-form-card.blade.php
- resources/views/components/sys/events/form-card.blade.php
- resources/views/livewire/portal/dashboard.blade.php
- resources/views/livewire/portal/home.blade.php
- resources/views/livewire/portal/register-event-attendance.blade.php
- resources/views/livewire/portal/register.blade.php
- resources/views/livewire/portal/virtual-card.blade.php
- resources/views/livewire/sys/events/events-table.blade.php
- resources/views/livewire/sys/events/virtual-card-setup-form.blade.php
Update the Portal module to enable registration of people and the attendance for one event, also update Sys/Event module to enable saving of virtual card template file and the virtual card setup. More info in commit of versions 1.4.2, 1.5.0, 1.6.0 and 1.7.0.
> Update Portal and Sys/Events modules (v1.4.2 to v1.7.0)

- app/Models/Sys/EventAttendance.php
Update the EventAttendance model to fix issue in 'cag_get_certificate' function, fix logical error - 09-01-2023
> v1.7.1 - Update EventAttendance model

- .env.example
- app/Utils/CommonUtils.php
- resources/views/pages/portal/certificates/certificate-pdf.blade.php
Actualizar la utilidad CommonUtils.php para agregar la funcioń 'get_public_path' este método ahora tiene en cuenta otro directorio público personalizado, para ello es necesario cambiar la variable 'PUBLIC_PATH' del archivo '.env'. Finalmente modificar plantilla certificate-pdf.blade y archivo .env-example
> Solucionar problema para cargar la marca de agua del certificado

- .env.example
- app/Utils/CommonUtils.php
- resources/views/livewire/portal/virtual-card.blade.php
- resources/views/pages/portal/certificates/certificate-pdf.blade.php
- routes/web.php
> Merge licinfo live into master

- app/Http/Controllers/Sys/EventAttendanceController.php
- app/Http/Requests/Sys/UpdateEventAttendanceRequest.php
- resources/views/livewire/sys/events/attendances/attendances-table.blade.php
- resources/views/sys/events/attendances/edit.blade.php
- routes/web.php
Add Event Attendance Management
- Introduced EventAttendanceController for handling event attendance editing and updating.
- Created UpdateEventAttendanceRequest for validating attendance update requests.
- Added a new Blade view for editing event attendance details.
- Updated routes to include edit and update functionalities for event attendances.
- Enhanced the attendances table to link to the edit page for better user navigation.
> Fix event attendance data editting.
